name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  variables:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: get go version
        id: go-version
        run: echo go-version=$(cat .go-version) >> $GITHUB_OUTPUT
    outputs:
      go-version: ${{ steps.go-version.outputs.go-version }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: install golang
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.variables.outputs.go-version }}
      - name: tests
        run: make test